name: Federação Mineira de Tênis de Mesa
markdown: redcarpet
pygments: true

baseurl: http://fmtm.net

permalink: pretty

paginate: 5
paginate_path: "pagina-:num"

excerpt_separator: "<!-- more -->"

last_event: "X Copa MG"

next_event: "XII Copa MG e III CMTM Individual"
next_event_url: "/2013/09/01/xii-copa-mg-e-iii-cmtm-individual/"

image_feed:
  - name: "X Copa MG"
    year: 2013
    pics: ["http://1.bp.blogspot.com/-AepHPbB2SUg/UiyNelS_8iI/AAAAAAAABw8/xWUYOUmoItk/s1600/DSC00303.JPG",
              "http://2.bp.blogspot.com/-i9T_EgdNVos/UiyNmBY4uFI/AAAAAAAABxE/BQxIdF9yJfI/s1600/DSC00306.JPG",
              "http://2.bp.blogspot.com/-TRsLlb9GbcM/UiyNoZXvS0I/AAAAAAAABxM/cZYa6mpRph8/s1600/DSC00308.JPG",
              "http://3.bp.blogspot.com/-emjz17btgDU/UiyNsGpnvuI/AAAAAAAABxU/za4KhBCI3Sk/s1600/DSC00307.JPG"]

  - name: "IX Copa MG e III Etapa CMTM Duplas"
    year: 2013
    pics: ["http://2.bp.blogspot.com/-0bu6tClIi2Y/UhOEcSNETkI/AAAAAAAABvo/CwSncWKVO8E/s1600/DSC00254.JPG",
        "http://1.bp.blogspot.com/-o8Q0SiBbLRM/UhOEbucjH7I/AAAAAAAABvk/KsJ7Ds2ZAkY/s1600/DSC00255.JPG",
        "http://1.bp.blogspot.com/-Y3J1iOjrCmA/UhOEfVej9DI/AAAAAAAABv0/B1PHlgrIS7g/s1600/DSC00256.JPG",
        "http://4.bp.blogspot.com/-XYzBEdNqQ48/UhOExL8MYPI/AAAAAAAABv8/veqdrj3g6Eg/s1600/DSC00257.JPG",
        "http://4.bp.blogspot.com/-AmezA_Y_YpI/UhOExoFU5BI/AAAAAAAABwE/KiEDlh-BJ9M/s1600/DSC00260.JPG",
        "http://2.bp.blogspot.com/-FPOMUKkkPlg/UhOEx4a4KgI/AAAAAAAABwI/HOP7hn3vzDA/s1600/DSC00261.JPG",
        "http://3.bp.blogspot.com/-BHLUAnh6n2c/UhOE90WzOLI/AAAAAAAABwU/HlOYp2UnecE/s1600/DSC00265.JPG",
        "http://1.bp.blogspot.com/-c2QY5Zkam5E/UhOE_a83gQI/AAAAAAAABwc/fBJj1AjJuho/s1600/DSC00267.JPG"]

  - name: "VIII Copa MG e II Etapa CMTM Individual"
    year: 2013
    pics: ["http://3.bp.blogspot.com/-xke93PgqCWc/UfvkqpNL4nI/AAAAAAAABqk/N6XCixg_bV0/s1600/27072013096.jpg",
        "http://1.bp.blogspot.com/-Jpf8bzXN-M4/UfvksnBKn7I/AAAAAAAABq0/op5GH9AoxUE/s1600/27072013097.jpg",
        "http://2.bp.blogspot.com/-Ik4KAokN5Q8/UfvksVtvOrI/AAAAAAAABqw/3O3MQ5G7urM/s1600/27072013098.jpg",
        "http://1.bp.blogspot.com/-zk37kzpdEoM/Ufvkx8DaTxI/AAAAAAAABq8/HJ2zK8GWsII/s1600/27072013099.jpg",
        "http://3.bp.blogspot.com/-StB9ewjQLOI/Ufvk0rX2XPI/AAAAAAAABrI/YUaNUTsVw3I/s1600/27072013103.jpg",
        "http://3.bp.blogspot.com/-i-QMfdGsUck/Ufvk0vG1ySI/AAAAAAAABrM/F25PZXyyWj0/s1600/27072013104.jpg",
        "http://1.bp.blogspot.com/-Vv7UTJ_7HeM/Ufvk7OJdpDI/AAAAAAAABrk/1NywjLahUko/s1600/27072013111.jpg",
        "http://2.bp.blogspot.com/-OFbXJpqVak0/Ufvk63kSPHI/AAAAAAAABrg/pVoFbC7NM-s/s1600/27072013116.jpg",
        "http://4.bp.blogspot.com/-5LptbzL3tqM/Ufvk61yOPXI/AAAAAAAABrc/H6rkC4TJQeM/s1600/27072013117.jpg",
        "http://4.bp.blogspot.com/-xKt6KcGbNUI/UfvlA5NcbHI/AAAAAAAABrs/07U-CWdWvu4/s1600/27072013118.jpg",
        "http://2.bp.blogspot.com/-fTsqtNApu-A/UfvlCaYJ4EI/AAAAAAAABr0/fm3wfWPIH9I/s1600/27072013120.jpg",
        "http://2.bp.blogspot.com/-A1d54XOus30/UfvlDqgQb7I/AAAAAAAABr8/srpHU6JtLI8/s1600/27072013121.jpg",
        "http://3.bp.blogspot.com/-lwD5JQQfz7A/UfvlIckvsxI/AAAAAAAABsM/vDDMt7eoBwg/s1600/28072013127.jpg",
        "http://3.bp.blogspot.com/-MJxMjbXk0ZM/UfvlH1XdIqI/AAAAAAAABsE/UWPbjIxoyAM/s1600/28072013130.jpg",
        "http://2.bp.blogspot.com/-j82vVxJ5BG8/UfvlMrAwy1I/AAAAAAAABsY/Mdlu17MfBWg/s1600/28072013131.jpg",
        "http://4.bp.blogspot.com/-Rs7Pd5AotlE/UfvlM4gut0I/AAAAAAAABsc/-kCpxNnKdFg/s1600/28072013132.jpg",
        "http://2.bp.blogspot.com/-nRjHj6oDAUY/UfvlNk3JU2I/AAAAAAAABsk/N8KFdFxm0RM/s1600/28072013134.jpg",
        "http://2.bp.blogspot.com/-r9psDotaXhk/UfvlS_XX_WI/AAAAAAAABs0/NlZOXaEroDE/s1600/28072013136.jpg",
        "http://1.bp.blogspot.com/-E9usYAjtlkI/UfvlST1kg0I/AAAAAAAABss/Y8lTQwPjLh0/s1600/28072013143.jpg",
        "http://4.bp.blogspot.com/-EP6fO9fyhqQ/UfvlVMUJ0kI/AAAAAAAABs8/SPBqghFS8NI/s1600/28072013139.jpg",
        "http://3.bp.blogspot.com/-R-6yis93mTY/UfvlXa3tZLI/AAAAAAAABtE/FC91kWIJ5Bc/s1600/28072013148.jpg",
        "http://1.bp.blogspot.com/-98vdjU4Yu2s/UfvmgQ9MO4I/AAAAAAAABtc/9TFTprCmTQ0/s1600/28072013144.jpg",
        "http://3.bp.blogspot.com/-hug4w8iwiFc/UfvmhGZAf5I/AAAAAAAABtk/MhDYbw3S7I0/s1600/28072013151.jpg",
        "http://4.bp.blogspot.com/-oMcArCBrLZI/UfvmmAIyMcI/AAAAAAAABt0/e6uFTDuvIWg/s1600/28072013152.jpg",
        "http://1.bp.blogspot.com/-n337LiKKVRg/UfvmlLEARUI/AAAAAAAABts/5M1SfIYecDw/s1600/28072013155.jpg",
        "http://2.bp.blogspot.com/-mj3klIkPkCs/Ufvmm_LmIPI/AAAAAAAABt8/K65OD5QTO98/s1600/28072013156.jpg",
        "http://3.bp.blogspot.com/-z1k5f7R_nGc/UfvmpEc8s4I/AAAAAAAABuE/-mAP6sVQCbo/s1600/28072013158.jpg"]

  - name: "VII Copa MG e II Etapa CMTM Equipes"
    year: 2013
    pics: ["http://2.bp.blogspot.com/-kj1RVuNx8IU/UeQvg773tuI/AAAAAAAABpA/OcwyOB_dkeI/s1600/DSC00254.JPG",
          "http://1.bp.blogspot.com/-vfE9FYE-N5Q/UeQvgnw-vtI/AAAAAAAABo4/3K0lYkgPBQI/s1600/DSC00255.JPG",
          "http://2.bp.blogspot.com/-CSGhTRDQ0gg/UeQvhMfWZwI/AAAAAAAABo8/boM4p5ru9Po/s1600/DSC00256.JPG",
          "http://3.bp.blogspot.com/-zwpxDsson74/UeQvjc43BtI/AAAAAAAABpQ/TngnRwNzpyE/s1600/DSC00257.JPG",
          "http://2.bp.blogspot.com/-YCp4lZPctbw/UeQvm9avYYI/AAAAAAAABpg/DOvMkHDP5iw/s1600/DSC00258.JPG",
          "http://1.bp.blogspot.com/-xt8kStWqPWA/UeQvlzUlaaI/AAAAAAAABpY/E32U5G8Xav8/s1600/DSC00259.JPG",
          "http://2.bp.blogspot.com/-6HWhIuSy2n8/UeQvnB5sTBI/AAAAAAAABpk/bV6qO4Ggpxs/s1600/DSC00260.JPG",
          "http://1.bp.blogspot.com/-I3u-iDoCK6U/UeQvp5RIi1I/AAAAAAAABpw/BAIoSCYLB5Q/s1600/DSC00261.JPG",
          "http://1.bp.blogspot.com/-UomAdsM3cXU/UeQvqrYATJI/AAAAAAAABp4/VGl-I5o3WVg/s1600/DSC00264.JPG",
          "http://3.bp.blogspot.com/-PCPvY_uPrWA/UeQvrDf7FSI/AAAAAAAABqA/fi8YgGN1mHM/s1600/DSC00266.JPG",
          "http://1.bp.blogspot.com/-E3pBHjqOQWQ/UeQvttksL1I/AAAAAAAABqI/7ixUExvdAsA/s1600/DSC00269.JPG",
          "http://1.bp.blogspot.com/-yVFTF4F3aTM/UeQvuB0UoSI/AAAAAAAABqQ/tLbaDErmif4/s1600/DSC00271.JPG"]

  - name: "VI Copa MG e II Etapa CMTM Duplas"
    year: 2013
    pics: ["http://1.bp.blogspot.com/--JkDtjgd4b4/UcssDAj1vVI/AAAAAAAABlA/xMFt0CNegYw/s1600/DSC00292.JPG",
          "http://1.bp.blogspot.com/-RtXir75WI7g/UcssDcCVapI/AAAAAAAABlE/p-JuXfUi71E/s1600/DSC00293.JPG",
          "http://1.bp.blogspot.com/-a12z2YBg9cM/UcssD_byAHI/AAAAAAAABlQ/U3MLCpPSEhA/s1600/DSC00294.JPG",
          "http://2.bp.blogspot.com/-6A2gZfoqbFw/UcssHXHaufI/AAAAAAAABlY/X_PHmRj-Ex4/s1600/DSC00295.JPG",
          "http://3.bp.blogspot.com/-o7qcUl8o9gg/UcssIzfgPcI/AAAAAAAABlo/Uhsx1Zdklkg/s1600/DSC00297.JPG",
          "http://2.bp.blogspot.com/-uQNhhvW1zz4/UcssIU6SIhI/AAAAAAAABlg/SOh9avZeUuY/s1600/IMG_9871.JPG",
          "http://4.bp.blogspot.com/-fb2J1i1jwdQ/UcssLng8TXI/AAAAAAAABlw/EbHLGOOWouM/s1600/IMG_9874.JPG",
          "http://3.bp.blogspot.com/-wuXJlynhX60/UcssMdjmCLI/AAAAAAAABl4/odbTyA4D37Y/s1600/IMG_9877.JPG",
          "http://1.bp.blogspot.com/-LN8AyjjE3rQ/UcssNNZgBcI/AAAAAAAABmA/MGa8BEPx_yM/s1600/IMG_9883.JPG",
          "http://4.bp.blogspot.com/-o2GpC4J14po/UcssPMZ-3_I/AAAAAAAABmI/ezxuNwD4hmI/s1600/IMG_9888.JPG",
          "http://2.bp.blogspot.com/-OyjWK_nzdZQ/UcssQGkjJ0I/AAAAAAAABmQ/P3_5DSi82Ns/s1600/IMG_9893.JPG",
          "http://4.bp.blogspot.com/-a2i39wGPJUs/UcssRBYOS9I/AAAAAAAABmY/qThwbIebywQ/s1600/IMG_9894.JPG",
          "http://3.bp.blogspot.com/-NO2lUqxnURE/UcssSbVd6bI/AAAAAAAABmg/NRo1SZO8wTI/s1600/IMG_9900.JPG",
          "http://3.bp.blogspot.com/-LkvYbiV058c/UcssUACmFKI/AAAAAAAABmo/cfcxfcIqkmg/s1600/IMG_9902.JPG",
          "http://4.bp.blogspot.com/-IcSPMKDjyY8/UcssU8ZvaEI/AAAAAAAABmw/CKxDlu3GDlM/s1600/IMG_9903.JPG",
          "http://1.bp.blogspot.com/-9rpMI6Yy9Ak/UcssWtNSDmI/AAAAAAAABm4/el5qnAeGzQM/s1600/IMG_9904.JPG",
          "http://4.bp.blogspot.com/-TVJ9PSKIo6s/UcssXRreVDI/AAAAAAAABnA/aQzO7rQsLlY/s1600/IMG_9907.JPG",
          "http://1.bp.blogspot.com/-zwIcXqCv6KQ/UcssZfU4UAI/AAAAAAAABnI/UC5GozawnRk/s1600/IMG_9908.JPG",
          "http://3.bp.blogspot.com/-hJoPLfrQgCM/UcsuNvzTqGI/AAAAAAAABoo/iu9AR9rya-w/s1600/IMG_9914.JPG",
          "http://4.bp.blogspot.com/-jIRz8y64Ork/Ucssdt4xbUI/AAAAAAAABng/-9aP58aiUEA/s1600/IMG_9916.JPG",
          "http://1.bp.blogspot.com/-h5NjHYyFZeo/UcsselsraiI/AAAAAAAABno/ccFk1FfZXnk/s1600/IMG_9926.JPG",
          "http://3.bp.blogspot.com/-zjWFiTsgRMY/UcssggQ5HOI/AAAAAAAABnw/Ka0znFAsabU/s1600/IMG_9927.JPG",
          "http://3.bp.blogspot.com/-lgFNb9QDYoM/UcsshT_tKtI/AAAAAAAABn4/mGfV83jT2WM/s1600/IMG_9930.JPG",
          "http://1.bp.blogspot.com/-8f9j_0lKjps/Ucsshwbi-ZI/AAAAAAAABn8/8XJqrqSG600/s1600/IMG_9931.JPG",
          "http://2.bp.blogspot.com/-zq70oDnYwFk/UcssjK7dWNI/AAAAAAAABoI/ZkvcPmdx4xg/s1600/IMG_9936.JPG",
          "http://4.bp.blogspot.com/-MBwF6S3JCsc/Ucssliz_aTI/AAAAAAAABoQ/_2QcDgpSvO8/s1600/IMG_9937.JPG",
          "http://1.bp.blogspot.com/-DtXVNljl4gk/UcsslxUwXPI/AAAAAAAABoU/cbTtBNTYOsw/s1600/IMG_9962.JPG",
          "http://2.bp.blogspot.com/-CwMZ7UIo8uU/Ucssb6dpgTI/AAAAAAAABnY/274NNs5C4OU/s1600/IMG_9915.JPG"]
  - name: "V Copa MG e I Etapa CMTM Individual"
    year: 2013
    pics: ["http://1.bp.blogspot.com/-1qhneiaPP30/UYfa7pujnaI/AAAAAAAABj0/-XcOPN2P0p0/s1600/DSC00237.JPG",
          "http://4.bp.blogspot.com/-dQVnvyYMPzw/UYfa99Pi-QI/AAAAAAAABkE/FMpS2ibstZo/s1600/DSC00239.JPG",
          "http://1.bp.blogspot.com/-j-CgAr3onXY/UYfa9FKTRTI/AAAAAAAABj8/Z-qf2mosXGQ/s1600/DSC00240.JPG",
          "http://3.bp.blogspot.com/-GfvsJm1zXKs/UYfa_G1LlDI/AAAAAAAABkM/LuATzzu4JMs/s1600/DSC00242.JPG",
          "http://3.bp.blogspot.com/-qCNJBYipkhE/UYfa_6Q7hvI/AAAAAAAABkU/W7yHtcbKZ9k/s1600/DSC00243.JPG",
          "http://2.bp.blogspot.com/-bHwfP5wjX24/UYfbBnkQzHI/AAAAAAAABkc/EhZHdrEw4L0/s1600/DSC00245.JPG"]

  - name: "IV Copa MG e I Etapa CMTM Equipes"
    year: 2013
    pics: ["http://4.bp.blogspot.com/-YwP229oZsWk/UW1UizyYI7I/AAAAAAAABh0/hLcHkBDzWqI/s1600/DSC00230.JPG",
          "http://1.bp.blogspot.com/-Y5ioZpeJcjc/UW1UijHxoKI/AAAAAAAABhw/NVwiG-Fsegk/s1600/DSC00233.JPG",
          "http://1.bp.blogspot.com/-jMDDTiwx19Q/UW1Uk2CluPI/AAAAAAAABiA/eFwrcd7q690/s1600/DSC00234.JPG",
          "http://3.bp.blogspot.com/-Iw2tKVuZPfs/UW1UmyFi9-I/AAAAAAAABiI/1ketKIwonI0/s1600/DSC00236.JPG",
          "http://2.bp.blogspot.com/-MWOAfvBXNWA/UW1Unss7S4I/AAAAAAAABiQ/7Stb8SVIKXk/s1600/DSC00237.JPG",
          "http://1.bp.blogspot.com/-tW6hTirCQPk/UW1UpVmYIrI/AAAAAAAABiY/mGqM1eJFb64/s1600/DSC00238.JPG",
          "http://2.bp.blogspot.com/-9iP_c5BYews/UW1UqpQtVSI/AAAAAAAABig/-He6b8JMNxY/s1600/DSC00239.JPG",
          "http://2.bp.blogspot.com/-4Q_cH0qrrd0/UW1UsS-s2FI/AAAAAAAABio/tlbXXNRqNMI/s1600/DSC00241.JPG",
          "http://4.bp.blogspot.com/-bDEGBNEkSow/UW1UtwFO1_I/AAAAAAAABiw/7fvdnUwnj5w/s1600/DSC00242.JPG",
          "http://3.bp.blogspot.com/-FI5x9wmkHb8/UW1UvtE5gGI/AAAAAAAABi4/4MlltZZrDGo/s1600/DSC00243.JPG",
          "http://2.bp.blogspot.com/-SAAnRfkp1VA/UW1Uw6zuUeI/AAAAAAAABjA/gM6-yG2GuOc/s1600/DSC00244.JPG",
          "http://4.bp.blogspot.com/-3Xd0xuwSwBw/UW1UyyVk5GI/AAAAAAAABjI/uAJbR2FKM0A/s1600/DSC00245.JPG",
          "http://4.bp.blogspot.com/-wd65yDUb0ic/UW1Uzksh6fI/AAAAAAAABjQ/c01GaZKdYG8/s1600/DSC00246.JPG",
          "http://1.bp.blogspot.com/-dutchwLI-5g/UW1U0T0tZjI/AAAAAAAABjY/qiTi3jLB4fQ/s1600/DSC00247.JPG"]
  - name: "III Copa MG Intersports"
    year: 2013
    pics: ["http://1.bp.blogspot.com/-RQ47tje7SLE/UVH9HTptLvI/AAAAAAAABeM/zBDSqy95v-g/s1600/DSC00128.JPG",
          "http://4.bp.blogspot.com/-ZxiA60Y4vok/UVH9J_lkUfI/AAAAAAAABeU/9TT4-j0xm-8/s1600/DSC00141.JPG",
          "http://2.bp.blogspot.com/--EFHniTg7nY/UVH9MeMpwrI/AAAAAAAABec/kVWPiY05iN4/s1600/DSC00142.JPG",
          "http://4.bp.blogspot.com/-JkxnhuR0YLk/UVH9MRhNRsI/AAAAAAAABeg/S1wVXbkEKzw/s1600/DSC00143.JPG",
          "http://4.bp.blogspot.com/-RawiiiCJXbQ/UVH9Mzkoj5I/AAAAAAAABes/1NGfTccHrWI/s1600/DSC00144.JPG",
          "http://3.bp.blogspot.com/-Q5tvaGF4z5g/UVH9Q8aqFxI/AAAAAAAABe0/5AacQoi2_Lo/s1600/DSC00145.JPG",
          "http://3.bp.blogspot.com/-6RXa_Vxw_uI/UVH9RRNeO-I/AAAAAAAABe8/dNlUML1TgZs/s1600/DSC00147.JPG",
          "http://4.bp.blogspot.com/-e8IBWMGliA8/UVH9RjV3IyI/AAAAAAAABfA/bfePv92in30/s1600/DSC00146.JPG",
          "http://1.bp.blogspot.com/-G9jJokhkmyc/UVH9VYddqAI/AAAAAAAABfM/sytI4E4IYs0/s1600/DSC00148.JPG",
          "http://4.bp.blogspot.com/-Wrb9odmLMLs/UVH9V2Zzo-I/AAAAAAAABfU/StGf5lbVbhw/s1600/DSC00149.JPG",
          "http://3.bp.blogspot.com/-c-zwzKZ-zJU/UVH9XXc4AYI/AAAAAAAABfc/HnxMiCwZGMc/s1600/DSC00150.JPG",
          "http://3.bp.blogspot.com/-_G8tBqZy0hc/UVH9aOdyBMI/AAAAAAAABfk/zY_ZvNX7tYs/s1600/DSC00155.JPG",
          "http://3.bp.blogspot.com/-e8GTlNt4jNo/UVH9a4mXsoI/AAAAAAAABfs/s6gYSFykhYM/s1600/DSC00156.JPG",
          "http://2.bp.blogspot.com/-bMjXkzxpX3U/UVH9cXu5P9I/AAAAAAAABf0/WAytMbycv4Q/s1600/DSC00158.JPG",
          "http://2.bp.blogspot.com/-KX6qAja5Lrw/UVH9ckBVaXI/AAAAAAAABf4/iAV_ePRZTCM/s1600/DSC00157.JPG",
          "http://1.bp.blogspot.com/-oX_SGOgQLDQ/UVH9e4Cc-HI/AAAAAAAABgE/YDU4bLL3fhs/s1600/DSC00159.JPG",
          "http://1.bp.blogspot.com/-MNrf6ql7JBA/UVH9hYvg1iI/AAAAAAAABgM/E2STxPesz2o/s1600/DSC00161.JPG",
          "http://2.bp.blogspot.com/-RarS49Fr_s0/UVH9j5MSn2I/AAAAAAAABgU/BtkXl3-vpps/s1600/DSC00165.JPG",
          "http://4.bp.blogspot.com/-635aR21ZGz0/UVH9nBXK6QI/AAAAAAAABgc/MsaEtauB28w/s1600/DSC00160.JPG",
          "http://1.bp.blogspot.com/-AOW0ykxWS5U/UVH9ouAz5VI/AAAAAAAABgk/5XfobxlQtkM/s1600/DSC00162.JPG",
          "http://2.bp.blogspot.com/-4BY1Mna5A6o/UVH9pvhUwqI/AAAAAAAABgs/igEWxan-EfU/s1600/DSC00166.JPG",
          "http://2.bp.blogspot.com/-uOoDA09Pogs/UVH9qcFZkAI/AAAAAAAABg0/Qj2QRXsQPqI/s1600/DSC00167.JPG",
          "http://3.bp.blogspot.com/-1Ls_ddBYltw/UVH9txkJsYI/AAAAAAAABg8/cHwPvIvR-9I/s1600/DSC00171.JPG",
          "http://3.bp.blogspot.com/-F-iFhKsP4vk/UVH9uBwq_RI/AAAAAAAABhA/uWwe-0juDJw/s1600/DSC00168.JPG",
          "http://1.bp.blogspot.com/-gftJHpnut4w/UVH9uWt7yzI/AAAAAAAABhM/B6NXzW-IyaU/s1600/DSC00172.JPG",
          "http://2.bp.blogspot.com/-tp20Nq2RSkM/UVH9xC1hAuI/AAAAAAAABhU/XQYh7vzearM/s1600/DSC00177.JPG",
          "http://2.bp.blogspot.com/-ldYb62qcyJo/UVH9yzHslbI/AAAAAAAABhc/JIU4NfX2Hwc/s1600/DSC00174.JPG"]

  - name: "II Copa MG e I Etapa CMTM Duplas"
    year: 2013
    pics: ["http://4.bp.blogspot.com/-CG4TXYocEJo/UUmuz_ikT3I/AAAAAAAABdA/OnCC4BTSYNo/s1600/DSC00125.JPG",
          "http://1.bp.blogspot.com/-9k9jxXhKcQw/UUmu0umvZ0I/AAAAAAAABdI/wT9-ppuNpCE/s1600/DSC00126.JPG",
          "http://3.bp.blogspot.com/-8P2Kl8cmFbM/UUmu1JQ8jSI/AAAAAAAABdQ/TeSLouWuwu0/s1600/DSC00127.JPG",
          "http://3.bp.blogspot.com/-qRIEdI3hrAk/UUmu37qDpOI/AAAAAAAABdY/MSlx4JsesUM/s1600/DSC00128.JPG",
          "http://1.bp.blogspot.com/-z3WGccqfQ5o/UUmu4e5V4uI/AAAAAAAABdc/tpJSclq2-PU/s1600/DSC00129.JPG",
          "http://4.bp.blogspot.com/-b7kZ_T--IK8/UUmu4zJP4XI/AAAAAAAABdk/sZDDyRZX1AA/s1600/DSC00130.JPG",
          "http://1.bp.blogspot.com/-YWS7nZ4NB5c/UUmu6PTJHWI/AAAAAAAABdw/MbAdY2JpOU0/s1600/DSC00132.JPG"]

  - name: "I Copa MG"
    year: 2013
    pics: ["http://2.bp.blogspot.com/-L1-hKZkx-F4/UT3wWOhwh3I/AAAAAAAABb8/1SHx6EKcJss/s1600/DSC00088.JPG",
          "http://1.bp.blogspot.com/-GbzZJni628A/UT3wX6_e3qI/AAAAAAAABcE/IpwVVqC_YRk/s1600/DSC00093.JPG",
          "http://4.bp.blogspot.com/-FroqOHux1OY/UT3wY4Z0OdI/AAAAAAAABcM/qDmm2haW-GE/s1600/DSC00095.JPG",
          "http://4.bp.blogspot.com/-zbM8gkffPD0/UT3waRgB5zI/AAAAAAAABcU/uHM5OdS0pH8/s1600/DSC00096.JPG",
          "http://3.bp.blogspot.com/-VJn-3i1NivA/UT3wahCMnJI/AAAAAAAABcY/ndtCPrco7T8/s1600/DSC00097.JPG",
          "http://3.bp.blogspot.com/-k212SEcIzEc/UT3wbvav6yI/AAAAAAAABck/k8fugzWG1sE/s1600/DSC00099.JPG"]
