name: Federação Mineira de Tênis de Mesa
markdown: redcarpet
pygments: true

baseurl: http://fmtm.net

permalink: pretty

paginate: 5
paginate_path: "pagina-:num"

excerpt_separator: "<!-- more -->"

last_event: "X Copa MG"

next_event: "XI Copa MG"
next_event_url: "/2013/09/11/eventos-xi-copa-mg-e-iii-cmtm-equipes/"
