name: Federação Mineira de Tênis de Mesa
markdown: redcarpet
pygments: true

baseurl: http://thiagokimo.github.io/fmtm-new

last_event: "X Copa MG"

last_event_pics: ["http://1.bp.blogspot.com/-AepHPbB2SUg/UiyNelS_8iI/AAAAAAAABw8/xWUYOUmoItk/s1600/DSC00303.JPG",
              "http://2.bp.blogspot.com/-i9T_EgdNVos/UiyNmBY4uFI/AAAAAAAABxE/BQxIdF9yJfI/s1600/DSC00306.JPG",
              "http://2.bp.blogspot.com/-TRsLlb9GbcM/UiyNoZXvS0I/AAAAAAAABxM/cZYa6mpRph8/s1600/DSC00308.JPG"]
